permalink: /:year/:month/:title/
markdown: kramdown
lsi: false
rouge: true
safe: true
auto: false 
author: Isaac
# Sidebar settings
sidebar: true  #添加侧边栏
sidebar-about-description: "简单的描述一下你自己"
sidebar-avatar: /media/image/images.jpeg
description: isaac's Blog, powered by Jekyll...
highlighter: rouge
timezone: Asia/Shanghai
gems: [jekyll-paginate]
paginate: 24

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
